=== karwowskiantoni/Semestr_III/Technologie XML/Laboratorium/filmy/XML,CSS,DTD/szablon.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT filmweb (Początek, MagazynFilmów, Platformy, Autor, DataOstatniejModyfikacji)>
<!ATTLIST Film 
    numer ID #REQUIRED
    gatunek CDATA #REQUIRED
    krajProdukcji CDATA #REQUIRED
    oskary CDATA #REQUIRED>
<!ELEMENT Film (Info+, Plakat*, Dostępność*)>

<!ELEMENT Info (Tytuł+, Reżyser, Ocena, Boxoffice, Sukces, Premiera)>

<!ATTLIST Tytuł 
    origin CDATA #REQUIRED>
<!ELEMENT Tytuł (#PCDATA)>

<!ELEMENT Reżyser ((Imię | Imiona)+, Nazwisko)>
<!ELEMENT Imię (#PCDATA)>
<!ELEMENT Imiona (#PCDATA)>
<!ELEMENT Nazwisko (#PCDATA)>

<!ELEMENT Ocena (Średnia, Głosów)>
<!ELEMENT Średnia (#PCDATA)>
<!ELEMENT Głosów (#PCDATA)>

<!ELEMENT Boxoffice (Całość, PierwszyTydzień, UdziałPierwszegoTygodnia, Budżet)>
<!ELEMENT Całość (#PCDATA)>
<!ATTLIST Całość
    waluta CDATA #FIXED "$">
<!ELEMENT PierwszyTydzień (#PCDATA)>
<!ATTLIST PierwszyTydzień
    waluta CDATA #FIXED "$">
<!ELEMENT UdziałPierwszegoTygodnia (#PCDATA)>
<!ATTLIST UdziałPierwszegoTygodnia
    jednostka CDATA #IMPLIED>
<!ELEMENT Budżet (#PCDATA)>

<!ELEMENT Sukces EMPTY>
<!ATTLIST Sukces
    value CDATA #REQUIRED>

<!ELEMENT Premiera (#PCDATA)>

<!ELEMENT Plakat EMPTY>
<!ATTLIST Plakat 
    plik ID #REQUIRED
    ścieżka CDATA #REQUIRED>  
<!ELEMENT Dostępność EMPTY>

<!ATTLIST Dostępność 
    platforma IDREF #REQUIRED>
<!ELEMENT Początek (#PCDATA)>
<!ELEMENT MagazynFilmów (Film*)>

<!ELEMENT Platformy (Platforma*)>
<!ELEMENT Platforma (#PCDATA)>
<!ATTLIST Platforma 
    link ID #REQUIRED>

<!ELEMENT Autor (Imię+, Nazwisko, NrAlbumu)>
<!ELEMENT NrAlbumu (#PCDATA)>
<!ELEMENT DataOstatniejModyfikacji (#PCDATA)>

=== karwowskiantoni/Semestr_III/Technologie XML/Laboratorium/filmy/ZadanieKPK2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!DOCTYPE filmweb SYSTEM "szablon.dtd"[
	<!ENTITY g1 "Dramat">
	<!ENTITY g2 "Biograficzny">
	<!ENTITY g3 "Komedia">
	<!ENTITY g4 "Gangsterski">
	<!ENTITY g5 "Psychologiczny">
	<!ENTITY g6 "Fantasy">
	<!ENTITY g7 "Kryminał">
	<!ENTITY g8 "Familijny">
	<!ENTITY g9 "Thriller">
	<!ENTITY g10 "Western">
	<!ENTITY g11 "Sci-Fi">
]>

<filmweb>
	<Początek>Top 30 filmów wg. użytkowników Filmweb</Początek>
	<MagazynFilmów>
		<Film numer="1" gatunek="&g1;" krajProdukcji="USA" oskary="0">
			<Info>
				<Tytuł origin="pl">Skazani na Shawshank</Tytuł>
				<Tytuł origin="org">The Shawshank Redemption</Tytuł>
				<Reżyser>
					<Imię>Frank</Imię>
					<Nazwisko>Darabont</Nazwisko>
				</Reżyser>
				<Ocena>
					<Średnia>8.76</Średnia>
					<Głosów>884670</Głosów>
				</Ocena>
				<Boxoffice>
					<Całość>59.841.469</Całość>
					<PierwszyTydzień>727.327</PierwszyTydzień>
					<UdziałPierwszegoTygodnia>2.6%</UdziałPierwszegoTygodnia>
					<Budżet>25.000.000</Budżet>
				</Boxoffice>
				<Sukces value="false"/>
				<Premiera>10 września 1994</Premiera>
			</Info>
			<Plakat plik="innocent.png" ścieżka="C:\Zdjęcia" />
			<Dostępność platforma="net"/> 
			
		</Film>

		<Film numer="2" gatunek="&g3;" krajProdukcji="Francja" oskary="0">
			<Info>
				<Tytuł origin="pl">Nietykalni</Tytuł>
				<Tytuł origin="org">Intouchables</Tytuł>
				<Reżyser>
					<Imię>Olivier</Imię>
					<Nazwisko>Nakache</Nazwisko>
				</Reżyser>
				<Ocena>
					<Średnia>8.63</Średnia>
					<Głosów>647237</Głosów>
				</Ocena>
				<Boxoffice>
					<Całość>426.588.510</Całość>
					<PierwszyTydzień>101.053</PierwszyTydzień>
					<UdziałPierwszegoTygodnia>0.8%</UdziałPierwszegoTygodnia>
					<Budżet>9.500.000</Budżet>
				</Boxoffice>
				<Sukces value="true"/>
				<Premiera>23 września 2011</Premiera>
			</Info>
			<Plakat plik="boogiewonderland.png" ścieżka="C:\Zdjęcia"/>
			<Dostępność platforma="cp"/>

		</Film>

		<Film numer="3" gatunek="&g1;" krajProdukcji="USA" oskary="0">
			<Info>
				<Tytuł origin="pl">Zielona Mila</Tytuł>
				<Tytuł origin="org">Green Mile</Tytuł>
				<Reżyser>
					<Imię>Frank</Imię>
					<Nazwisko>Darabont</Nazwisko>
				</Reżyser>
				<Ocena>
					<Średnia>8.60</Średnia>
					<Głosów>969502</Głosów>
				</Ocena>
				<Boxoffice>
					<Całość>286.801.374</Całość>
					<PierwszyTydzień>18.017.152</PierwszyTydzień>
					<UdziałPierwszegoTygodnia>13.2%</UdziałPierwszegoTygodnia>
					<Budżet>60.000.000</Budżet>
				</Boxoffice>
				<Sukces value="true"/>
				<Premiera>6 grudnia 1999</Premiera>
			</Info>
			<Plakat plik="coffeynotcoffe.png" ścieżka="C:\Zdjęcia"/>
			<Dostępność platforma="net"/>
		</Film>

		<Film numer="4" gatunek="&g4;" krajProdukcji="USA" oskary="3">
			<Info>
				<Tytuł origin="pl">Ojciec Chrzestny</Tytuł>
				<Tytuł origin="org">The Godfather</Tytuł>
				<Reżyser>
					<Imię>Francis</Imię>
					<Imię>Ford</Imię>
					<Nazwisko>Coppola</Nazwisko>
				</Reżyser>
				<Ocena>
					<Średnia>8.59</Średnia>
					<Głosów>521237</Głosów>
				</Ocena>
				<Boxoffice>
					<Całość>245.066.411</Całość>
					<PierwszyTydzień>302.393</PierwszyTydzień>
					<UdziałPierwszegoTygodnia>0.2%</UdziałPierwszegoTygodnia>
					<Budżet>6.000.000</Budżet>
				</Boxoffice>
				<Sukces value="true"/>
				<Premiera>15 marca 1972</Premiera>
			</Info>
			<Plakat plik="cantrefuseoffer.png" ścieżka="C:\Zdjęcia"/>
			<Dostępność platforma="net"/>					
		</Film>

		<Film numer="5" gatunek="&g1;" krajProdukcji="USA" oskary="0">
			<Info>
				<Tytuł origin="pl">Dwunastu gniewnych ludzi</Tytuł>
				<Tytuł origin="org">12 Angry Men</Tytuł>
				<Reżyser>
					<Imię>Sidney</Imię>
					<Nazwisko>Lumet</Nazwisko>
				</Reżyser>
				<Ocena>
					<Średnia>8.55</Średnia>
					<Głosów>210034</Głosów>
				</Ocena>
				<Boxoffice>
					<Całość>2.000.000</Całość>
					<PierwszyTydzień>20.000</PierwszyTydzień>
					<UdziałPierwszegoTygodnia>1.0%</UdziałPierwszegoTygodnia>
					<Budżet>340.000</Budżet>
				</Boxoffice>
				<Sukces value="true"/>
				<Premiera>10 kwietnia 1957</Premiera>
			</Info>
			<Plakat plik="guilty.png" ścieżka="C:\Zdjęcia"/>
			<Dostępność platforma="cda"/>			
		</Film>

		<Film numer="6" gatunek="&g1;" krajProdukcji="USA" oskary="6">
			<Info>
				<Tytuł origin="pl">Forrest Gump</Tytuł>
				<Tytuł origin="org">Forrest Gump</Tytuł>
				<Reżyser>
					<Imię>Robert</Imię>
					<Nazwisko>Zemeckis</Nazwisko>
				</Reżyser>
				<Ocena>
					<Średnia>8.52</Średnia>
					<Głosów>958936</Głosów>
				</Ocena>
				<Boxoffice>
					<Całość>2.683.095.371</Całość>
					<PierwszyTydzień>24.450.602</PierwszyTydzień>
					<UdziałPierwszegoTygodnia>7.4%</UdziałPierwszegoTygodnia>
					<Budżet>55.000.000</Budżet>
				</Boxoffice>
				<Sukces value="true"/>
				<Premiera>24 czerwca 1994</Premiera>
			</Info>
			<Plakat plik="runforrest.png" ścieżka="C:\Zdjęcia"/>
			<Dostępność platforma="hbo"/>		
		</Film>

		<Film numer="7" gatunek="&g1;" krajProdukcji="USA" oskary="5">
			<Info>
				<Tytuł origin="pl">Lot nad kukułczym gniazdem</Tytuł>
				<Tytuł origin="org">One Flew Over the Cuckoo's Nest</Tytuł>
				<Reżyser>
					<Imię>Milos</Imię>
					<Nazwisko>Forman</Nazwisko>
				</Reżyser>
				<Ocena>
					<Średnia>8.44</Średnia>
					<Głosów>384609</Głosów>
				</Ocena>
				<Boxoffice>
					<Całość>108.981.275</Całość>
					<PierwszyTydzień>99.761</PierwszyTydzień>
					<UdziałPierwszegoTygodnia>0.1%</UdziałPierwszegoTygodnia>
					<Budżet>3.000.000</Budżet>
				</Boxoffice>
				<Sukces value="true"/>
				<Premiera>19 listopada 1975</Premiera>
			</Info>
			<Plakat plik="cuckoo.png" ścieżka="C:\Zdjęcia"/>
			<Dostępność platforma="cda"/>
		</Film>

		<Film numer="8" gatunek="&g4;" krajProdukcji="USA" oskary="6">
			<Info>
				<Tytuł origin="pl">Ojciec Chrzestny II</Tytuł>
				<Tytuł origin="org">The Godfather: Part II</Tytuł>
				<Reżyser>
					<Imię>Francis</Imię>
					<Imię>Ford</Imię>
					<Nazwisko>Coppola</Nazwisko>
				</Reżyser>
				<Ocena>
					<Średnia>8.38</Średnia>
					<Głosów>267910</Głosów>
				</Ocena>
				<Boxoffice>
					<Całość>286.801.374</Całość>
					<PierwszyTydzień>406.533</PierwszyTydzień>
					<UdziałPierwszegoTygodnia>0.3%</UdziałPierwszegoTygodnia>
					<Budżet>13.000.000</Budżet>
				</Boxoffice>
				<Sukces value="true"/>
				<Premiera>12 grudnia 1974</Premiera>
			</Info>
			<Plakat plik="fredoyoubrokemyheart.png" ścieżka="C:\Zdjęcia"/>
			<Dostępność platforma="net"/>			
		</Film>

		<Film numer="9" gatunek="&g8;" krajProdukcji="USA" oskary="7">
			<Info>
				<Tytuł origin="pl">Lista Schindlera</Tytuł>
				<Tytuł origin="org">Schindler's List</Tytuł>
				<Reżyser>
					<Imię>Steven</Imię>
					<Nazwisko>Spielberg</Nazwisko>
				</Reżyser>
				<Ocena>
					<Średnia>8.33</Średnia>
					<Głosów>353984</Głosów>
				</Ocena>
				<Boxoffice>
					<Całość>322.139.355</Całość>
					<PierwszyTydzień>656.636</PierwszyTydzień>
					<UdziałPierwszegoTygodnia>0.7%</UdziałPierwszegoTygodnia>
					<Budżet>22.000.000</Budżet>
				</Boxoffice>
				<Sukces value="true"/>
				<Premiera>30 listopada 1993</Premiera>
			</Info>
			<Plakat plik="redjacket.png" ścieżka="C:\Zdjęcia"/>
			<Dostępność platforma="cda"/>		
		</Film>

		<Film numer="10" gatunek="&g6;" krajProdukcji="USA" oskary="10">
			<Info>
				<Tytuł origin="pl">Władca Pierścieni: Powrót Króla</Tytuł>
				<Tytuł origin="org">The Lord of the Rings: The Return of the King</Tytuł>
				<Reżyser>
					<Imię>Peter</Imię>
					<Nazwisko>Jackson</Nazwisko>
				</Reżyser>
				<Ocena>
					<Średnia>8.33</Średnia>
					<Głosów>504231</Głosów>
				</Ocena>
				<Boxoffice>
					<Całość>1.141.999.888</Całość>
					<PierwszyTydzień>172.629</PierwszyTydzień>
					<UdziałPierwszegoTygodnia>9.2%</UdziałPierwszegoTygodnia>
					<Budżet>94.000.000</Budżet>
				</Boxoffice>
				<Sukces value="true"/>
				<Premiera>1 grudnia 2003</Premiera>
			</Info>
			<Plakat plik="rohanwillanswer.png" ścieżka="C:\Zdjęcia"/>
			<Dostępność platforma="net"/>			
		</Film>

		<Film numer="11" gatunek="&g4;" krajProdukcji="USA" oskary="1">
			<Info>
				<Tytuł origin="pl">Pulp Fiction</Tytuł>
				<Tytuł origin="org">Pulp Fiction</Tytuł>
				<Reżyser>
					<Imię>Quentin</Imię>
					<Nazwisko>Tarantino</Nazwisko>
				</Reżyser>
				<Ocena>
					<Średnia>8.32</Średnia>
					<Głosów>642086</Głosów>
				</Ocena>
				<Boxoffice>
					<Całość>213.928.762</Całość>
					<PierwszyTydzień>9.311.882</PierwszyTydzień>
					<UdziałPierwszegoTygodnia>8.6%</UdziałPierwszegoTygodnia>
					<Budżet>8.000.000</Budżet>
				</Boxoffice>
				<Sukces value="true"/>
				<Premiera>10 września 1994</Premiera>
			</Info>
			<Plakat plik="goldenwatch.png" ścieżka="C:\Zdjęcia"/>
			<Dostępność platforma="hbo"/>			
		</Film>

		<Film numer="12" gatunek="&g1;" krajProdukcji="USA" oskary="2">
			<Info>
				<Tytuł origin="pl">Joker</Tytuł>
				<Tytuł origin="org">Joker</Tytuł>
				<Reżyser>
					<Imię>Todd</Imię>
					<Nazwisko>Phillips</Nazwisko>
				</Reżyser>
				<Ocena>
					<Średnia>8.30</Średnia>
					<Głosów>240332</Głosów>
				</Ocena>
				<Boxoffice>
					<Całość>1.074.251.311</Całość>
					<PierwszyTydzień>96.202.337</PierwszyTydzień>
					<UdziałPierwszegoTygodnia>9.3%</UdziałPierwszegoTygodnia>
					<Budżet>55.000.000</Budżet>
				</Boxoffice>
				<Sukces value="true"/>
				<Premiera>31 sierpnia 2019</Premiera>
			</Info>
			<Plakat plik="youwouldntgetit.png" ścieżka="C:\Zdjęcia"/>
			<Dostępność platforma="cda"/>		
		</Film>

		<Film numer="13" gatunek="&g1;" krajProdukcji="Włochy" oskary="3">
			<Info>
				<Tytuł origin="pl">Życie jest piękne</Tytuł>
				<Tytuł origin="org">La vita è bella</Tytuł>
				<Reżyser>
					<Imię>Roberto</Imię>
					<Nazwisko>Benigni</Nazwisko>
				</Reżyser>
				<Ocena>
					<Średnia>8.29</Średnia>
					<Głosów>273850</Głosów>
				</Ocena>
				<Boxoffice>
					<Całość>229.163.264</Całość>
					<PierwszyTydzień>118.920</PierwszyTydzień>
					<UdziałPierwszegoTygodnia>0.2%</UdziałPierwszegoTygodnia>
